.TH utilsbox 1 2026-08-13

.SH NAME
utilsbox \- Набор маленьких утилит для linux
.SH SYNOPSIS
.B utilsbox
.SH DESCRIPTION
.B utilsbox
многофункциональная утилита, для доступа к каждой выделенной функции обращение через arg[0] или arg[1].
.B utilsbox ps
выводит снимок статусов процессов, как это делает ps(1).
