#!/usr/bin/env bash

NAME=myapp
VERSION=$(shell git describe --tags --always)
TOPDIR=$(CURDIR)/.rpmbuild   # свой топдир на проект
SPEC=$(NAME).spec
DIST=$(TOPDIR)/SOURCES/$(NAME)-$(VERSION).tar


make all

mkdir -p $(TOPDIR)/SOURCES
tar -cf $(TOPDIR)/SOURCES/$(NAME)-$(VERSION).tar -C . target/release/hx runtime/
rpmbuild --define '_topdir $(TOPDIR)' -bb $(SPEC)   # %build в спеке пустой